version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "haoming-sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vss6o86ez24f"
s3_prefix = "haoming-sam-test"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
